version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27001:27017  # 将MongoDB的默认端口映射到宿主机的27001端口上来
    volumes:         # 数据持久化配置
      - /home/mongotest:/data/db    # 将容器内部的数据映射到宿主机的home文件夹的mongotest文件夹里~

  redis-test:
    image: redis
    restart: always
    container_name: 'redis-test'
    ports: 
      - 15000:6379
    volumes:
      - /home/redistest:/data
    command: ["redis-test", "--requirepass", "123456"]